# Generated by Django 4.2.7 on 2023-12-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_delete_busprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busprofile',
            fields=[
                ('bno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=100, null=True)),
                ('phno', models.IntegerField()),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
