# Generated by Django 4.2.7 on 2023-12-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0015_stopname_delete_time_busprofile_usstopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='busprofile',
            name='stoptime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
