# Generated by Django 4.2.7 on 2023-12-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0018_busprofile_endstopname_busprofile_endstoptime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busprofile',
            old_name='atstoptime',
            new_name='ststoptime',
        ),
    ]
