# Generated by Django 4.2.7 on 2024-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0025_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busprofile',
            name='ststopname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
