# Generated by Django 4.2.7 on 2024-01-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0036_remove_uprofile_password1_remove_uprofile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busprofile',
            name='urname',
        ),
        migrations.AddField(
            model_name='route',
            name='brname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.busprofile'),
        ),
        migrations.AddField(
            model_name='route',
            name='stopname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='stoptime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Uprofile',
        ),
    ]
