# Generated by Django 4.2.7 on 2024-01-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0037_remove_busprofile_urname_route_brname_route_stopname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stopname',
        ),
        migrations.RemoveField(
            model_name='route',
            name='brname',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stopname',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stoptime',
        ),
    ]
