# Generated by Django 4.2.7 on 2023-12-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_rename_fname_busprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busprofile',
            name='bname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
