# Generated by Django 4.2.7 on 2023-12-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_remove_busprofile_rt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busprofile',
        ),
    ]
