# Generated by Django 4.2.7 on 2023-12-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0011_remove_busprofile_email_remove_busprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busprofile',
            name='password',
        ),
    ]
