# Generated by Django 4.2.7 on 2023-12-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_rename_stoptime_busprofile_atstoptime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busprofile',
            name='endstopname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='endstoptime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop2name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop3name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop3time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop4name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop4time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop5name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busprofile',
            name='stop5time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
