# Generated by Django 4.2.7 on 2023-12-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0021_busprofile_stop6name_busprofile_stop6time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=50)),
                ('busno', models.CharField(max_length=50)),
                ('update', models.CharField(max_length=200)),
            ],
        ),
    ]
