# Generated by Django 4.2.7 on 2024-01-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0032_remove_uprofile_name_remove_uprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uprofile',
        ),
    ]
