# Generated by Django 4.2.7 on 2024-01-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0034_uprofile_busprofile_urname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='uprofile',
            name='phno',
        ),
    ]
