# Generated by Django 4.2.7 on 2024-01-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0035_remove_uprofile_bio_remove_uprofile_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uprofile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='uprofile',
            name='password2',
        ),
    ]
