# Generated by Django 4.2.7 on 2023-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_remove_busprofile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='time',
        ),
    ]
