# Generated by Django 4.2.7 on 2023-12-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopname', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('busname', models.CharField(max_length=100)),
                ('busno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.busprofile')),
            ],
        ),
    ]
