# Generated by Django 4.2.7 on 2023-12-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopname',
            fields=[
                ('stopname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='time',
        ),
        migrations.AddField(
            model_name='busprofile',
            name='usstopname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.stopname'),
        ),
    ]
