# Generated by Django 4.2.7 on 2024-01-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0039_stopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopname',
            name='routename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.route'),
        ),
    ]
