# Generated by Django 4.2.7 on 2023-12-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_route_busprofile_rt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busprofile',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='busprofile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
