# Generated by Django 4.2.7 on 2023-12-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_busprofile_bname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busprofile',
            old_name='pass1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='busprofile',
            old_name='user',
            new_name='username',
        ),
    ]
