# Generated by Django 4.2.7 on 2023-12-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_rename_pass1_busprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busprofile',
            name='rt',
        ),
    ]
