# Generated by Django 4.2.7 on 2024-01-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0024_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
