# Generated by Django 4.2.7 on 2024-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0030_delete_article_alter_busprofile_ststopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busprofile',
            name='ststopname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
